version: "3"

services:
  web:
    image: trezonalecomte/shopshare-server:0.2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE=host=db user=shopshare
    ports:
      - "80:80"
    networks:
      - webnet

  db:
    image: postgres:9.6

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
